@startuml

package Mochila {

    class Estoque {
        - capMax : int
        - capUtil : int
        - produtos : List<Produto>

        + getCapMax() : int
        + setCapMax() : void
        + addEstoque(produto : Produto) : void
        + capRest() : int
        + otimizarEstoque(todosProdutos : List<Produto>) : void
    }

    class Produto {
        - nome : String
        - valor : double
        - peso : int
        - qnt : int
        - pesoTot : int

        + setValor(valor : double) : void
        + setPeso(peso : int) : void
        + setQnt(qnt : int) : void
        + getNome() : String
        + getValor() : int
        + getPeso() : int
        + getQnt() : int
        + calcTotal() : int
        + getValorPorPeso() : int
    }

    Estoque --> Produto : "produtos"
}

@enduml
